name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md' # any .md anywhere
  pull_request:
    paths-ignore:
      - '**/*.md' # any .md anywhere

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean cache
        run: npm cache clean --force

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Clone matterbridge repo
        run: git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge.git ../matterbridge

      - name: Install matterbridge dependencies
        working-directory: ../matterbridge
        run: npm ci --no-fund --no-audit

      - name: Build matterbridge
        working-directory: ../matterbridge
        run: npm run build

      - name: Link matterbridge globally
        working-directory: ../matterbridge
        run: npm link --no-fund --no-audit

      - name: Install plugin dependencies
        run: npm ci

      - name: Link matterbridge in the project
        run: npm link matterbridge

      - name: Lint the plugin
        run: npm run lint

      - name: Test the plugin
        run: npm run test -- --forceExit

      - name: Build the plugin
        run: npm run build
